server:
  port: 3344

eureka:
  client:
    #表示是否将自己注册进Eurekaserver默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka # 单个注册中心
      #defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka # 注册中心集群
  instance:
    instance-id: user8001 # 在注册中心的别名
    prefer-ip-address: true # 显示IP地址





spring:
  application:
    name: config-service

  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver        # #mysql驱动包
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding-utr-8&useSSL=false
    username: root
    password: root

  cloud:
    config:
      server:
        git:
          uri: https://github.com/yangjuhao/springcloud-config.git # git上面项目名称
          # 搜索目录
          search-paths:
            - springcloud-config
      # 读取分支
      label: master

